### ISSUE TITLE
da speed argumenty bei da gify

### ISSUE THREAD

**Issue by Jerrynicki** [M3IY0U/StalkbotGUI#11]
moin da bimoy

kannst du uh da machy dass man bei da fls!gify da argumenty geben kann für da speedy

also so saj!gif 5 und dann macht 5 mal so schnell weißte

weil das is dann da funny für da memeyj und so

mfg jrery schön tag noch

ps im anhang findet sich ein bild

![Untitled](https://user-images.githubusercontent.com/38357030/109500043-01464e80-7a96-11eb-83f8-4b0a1e77210b.png)

**Comment by TheLastZombie** [comment]
based

**Comment by M3IY0U** [comment]
bro

**Comment by Nihilopia** [comment]
:ablobheadshake:

**Comment by M3IY0U** [comment]
Alright nvm I guess this was kinda implemented via #22
