### ISSUE TITLE
Add microphone command

### ISSUE THREAD

**Issue by annadess** [M3IY0U/StalkbotGUI#13]
My suggestion would be a mic command that lets you record a short sound snippet and send that to discord, would be a funny feature to have in combination with the webcamgif or just as standalone feature for when you want to say "jerry stop playing silvagunner mashups through my bot for one hour straight, I will literally come to your house and drink your coffee"

**Comment by Jerrynicki** [comment]
hey wtf

**Comment by M3IY0U** [comment]
Closed in #17
